// Code generated by "stringer -type=itemType"; DO NOT EDIT.

package got

import "fmt"

const _itemType_name = "itemIgnoreitemErroritemStrictBlockitemNamedBlockitemEndBlockitemSubstituteitemIncludeitemEnditemConvertitemGoitemTextitemRunitemStringitemBoolitemIntitemUIntitemFloatitemInterfaceitemBytesitemCommentitemEOFitemBackup"

var _itemType_index = [...]uint8{0, 10, 19, 34, 48, 60, 74, 85, 92, 103, 109, 117, 124, 134, 142, 149, 157, 166, 179, 188, 199, 206, 216}

func (i itemType) String() string {
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return fmt.Sprintf("itemType(%d)", i)
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
