package main

import (
	"flag"
	"fmt"
	"github.com/spekary/got/got"
	"io/ioutil"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"go/build"
)

func processFile(file string) string {
	var s string

	for _, f := range got.IncludeFiles {
		buf, err := ioutil.ReadFile(f)
		if err != nil {
			fmt.Println(err)
			return ""
		}
		s += string(buf[:])
	}

	buf, err := ioutil.ReadFile(file)

	if err != nil {
		fmt.Println(err)
		return ""
	}
	s += string(buf[:])

	/*
		defer func() {
			if r := recover(); r != nil {
				fmt.Println("Recovered ", r)
			}
		}()*/

	s = ProcessString(s, file)
	if s != "" {
		s = "//** This file was code generated by got. ***\n\n\n" + s
	}
	return s
}

func writeFile(s string, file string, outDir string, runImports bool) {

	dir := filepath.Dir(file)
	dir, _ = filepath.Abs(dir)
	file = filepath.Base(file)

	i := strings.LastIndex(file, ".")

	if i < 0 {
		file = file + ".go"
	} else {
		file = file[:i] + ".go"
	}

	if outDir != "" {
		dir = outDir
	}

	if dir != "/" {
		dir = dir + "/"
	}
	file = dir + file

	ioutil.WriteFile(file, []byte(s), os.ModePerm)

	if runImports {
		execCommand("goimports -w " + file)
	} else {
		execCommand("go fmt " + file) // at least format it if we are not going to run imports on it
	}
}

//Process a string that is a got template, and return the go code
func ProcessString(input string, fileName string) string {
	l := got.Lex(input, fileName)

	s := got.Parse(l)

	return s
}

// execCommand wraps exec.Command
func execCommand(command string) {
	parts := strings.Split(command, " ")
	if len(parts) == 0 {
		return
	}

	cmd := exec.Command(parts[0], parts[1:]...)
	cmd.Stderr = os.Stderr

	err := cmd.Run()
	if err != nil {
		fmt.Println(err)
	}
}

var args string	// A neat little trick to directly test the main function. If we are testing, this will get set.

func main() {
	var outDir string
	var typ string
	var runImports bool
	var includes string
	var inputDirectory string

	flag.StringVar(&outDir, "o", "", "Output directory")
	flag.StringVar(&typ, "t", "", "Will process all files with this suffix in current directory, or the directory given by the -d directive.")
	flag.BoolVar(&runImports, "i", false, "Run goimports on the file to automatically add your imports to the file. You will need to install goimports to do this.")
	flag.StringVar(&includes, "I", "", "The list of directories to look in to find template include files. Separate with semicolons.")
	flag.StringVar(&inputDirectory, "d", "", "The directory to search for files if using the -t directive. Otherwise the current directory will be searched.")
	if args == "" {
		flag.Parse() // regular run of program
	} else {
		// test run
		flag.CommandLine.Parse(strings.Split(args, " "))
	}
	files := flag.Args()

	if len(os.Args[1:]) == 0 {
		fmt.Println("got processes got template files, turning them into go code to use in your application.")
		fmt.Println("Usage: got [-o outDir] [-t fileType] [-i] [-I includeDirs] file1 [file2 ...] ")
		fmt.Println("-o: send processed files to the given directory. Otherwise sends to the same directory that the template is in.")
		fmt.Println("-t: process all files with this suffix in the current directory. Otherwise, specify specific files at the end.")
		fmt.Println("-i: run goimports on the result files to automatically fix up the import statement and format the file. You will need goimports installed.")
		fmt.Println("-I: the list of directories to search for include files, or files to prepend before every processed file. Files are searched in the order given, and first one found will be used.")
		fmt.Println("-d: The directory to search for files if using the -t directive.")
	}

	got.IncludePaths = []string{}
	got.IncludeFiles = []string{}
	if includes != "" {
		i := strings.Split(includes, ";")
		for _, i2 := range i {
			path := getRealPath(i2)
			if fi, err := os.Stat(path); err != nil {
				fmt.Println("Include path " + path + " does not exist.")
			} else if fi.IsDir() {
				got.IncludePaths = append(got.IncludePaths, path)
			} else {
				got.IncludeFiles = append(got.IncludeFiles, path)
			}
		}
	}

	if inputDirectory != "" {
		inputDirectory = getRealPath(inputDirectory)
		if inputDirectory[len(inputDirectory)-1] != filepath.Separator {
			inputDirectory += string(filepath.Separator)
		}
	}

	if inputDirectory == "" {
		got.IncludePaths = append(got.IncludePaths, getRealPath("."))
	} else {
		got.IncludePaths = append(got.IncludePaths, inputDirectory)
	}

	outDir = getRealPath(outDir)

	dstInfo, err := os.Stat(outDir)
	if err != nil {
		panic(fmt.Sprintf("The output directory %s does not exist. Create the output directory and run it again.", outDir))
	}

	if !dstInfo.Mode().IsDir() {
		panic("The output directory specified is not a directory")
	}

	//var err error

	if typ != "" {
		files, _ = filepath.Glob(inputDirectory + "*." + typ)
	}

	for _, file := range files {
		s := processFile(file)
		if s != "" {
			writeFile(s, file, outDir, runImports)
		}
	}
}

func getRealPath(path string) string {
	path = filepath.FromSlash(path)
	if strings.Index(path, "GOPATH") == 0 {
		path = goPath() + path[6:]
	}

	var err error
	path, err = filepath.Abs(path)
	if err != nil {
		panic(err)
	}
	return path
}

func goPath() string {
	var path string
	goPaths := strings.Split(os.Getenv("GOPATH"), string(os.PathListSeparator))
	if len(goPaths) == 0 {
		path = build.Default.GOPATH
	} else if goPaths[0] == "" {
		path = build.Default.GOPATH
	} else {
		path = goPaths[0]
	}

	// clean path so it does not end with a path separator
	if path[len(path)-1] == os.PathSeparator {
		path = path[:len(path)-1]
	}

	// If the GOPATH is empty, then see if the current executable looks like it is in a project
	if path == "" {
		if path2, err := os.Executable(); err == nil {
			path2 = filepath.Join(filepath.Dir(filepath.Dir(path2)), "src")
			dstInfo, err := os.Stat(path)
			if err == nil && dstInfo.IsDir() {
				path = path2
			}
		}
	}

	path,_ = filepath.Abs(path)

	// TODO: GoPath may go away, so we might need to use another way to search for the current go project structure
	return path
}

