//** This file was code generated by GoT. DO NOT EDIT. ***


package template

import (
	"io"
	"fmt"
)

func includeFailedTest(_w io.Writer) (err error) {

if _,err = io.WriteString(_w, `abc
`); err != nil {return}



