//** This file was code generated by got. ***

package testOut

import (
	"bytes"
)

type Translater interface {
	Translate(string, *bytes.Buffer)
}

func TestStatic(buf *bytes.Buffer) {

	buf.WriteString(`Here `)
	buf.WriteString("is")
	buf.WriteString(` some code wrapping text escaping to go.`)

	buf.WriteString(`<p>
`)

	buf.WriteString(`Escaped html &lt;`)

	buf.WriteString(`
</p>
`)

	buf.WriteString(`<p>This is text<br>
	that is both escaped and has<br>
	html paragraphs and breaks inserted.<br>
</p>
`)

}

func translateTest(t Translater, buf *bytes.Buffer) {

	t.Translate(`Translate me to some language`, buf)

	t.Translate(`Translate &amp; escape me &gt;`, buf)

}
