//** This file was code generated by got. ***

package testOut

import (
	"bytes"
	"fmt"
)

func TestSub(buf *bytes.Buffer) {

	buf.WriteString(`	Print me.
`)

	myTest2(buf)
}

func myTest2(buf *bytes.Buffer) {

	buf.WriteString(`Substituted:
`)

	fmt.Println("Here is some go code.")

	buf.WriteString(`Here is some text to print
`)

}
