//** This file was code generated by got. ***

package testOut

import (
	"bytes"
	"strconv"
)

func givesStringWithErr() (string, error) {
	return "Me with no escaping", nil
}

func givesIntWithErr() (int, error) {
	return -5, nil
}

func givesFloatWithErr() (float32, error) {
	return 6.4, nil
}

func TestVarsWithErr(buf *bytes.Buffer) error {

	buf.WriteString("Evaluates to a string")

	buf.WriteString(`Here is the number: `)

	{
		v, err := givesIntWithErr()
		buf.WriteString(strconv.Itoa(v))
		if err != nil {
			return err
		}
	}

	buf.WriteString(`
And another: `)

	{
		v, err := givesStringWithErr()
		buf.WriteString(v)
		if err != nil {
			return err
		}
	}

	buf.WriteString(`
And a float: `)

	{
		v, err := givesFloatWithErr()
		buf.WriteString(strconv.FormatFloat(float64(v), 'g', -1, 64))
		if err != nil {
			return err
		}
	}

	buf.WriteString(`
`)

	return nil // no err
}
