name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go: [1.16, 1.17]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
        
    - name: Install Go Imports
      run: go install golang.org/x/tools/cmd/goimports@latest

    - name: Build
      run: go install

    - name: Test
      run: 
        go test -v -cover ./... -coverprofile coverage.out -coverpkg ./...
        go tool cover -func=coverage.out -o=coverage.out

    - name: Go Coverage Badge
      uses: tj-actions/coverage-badge-go@v1
      if: ${{ runner.os == 'Linux' }}
      with:
        filename: coverage.out
        
    - name: Verify Changed files
      uses: tj-actions/verify-changed-files@v8.1
      id: verify-changed-files
      with:
        files: README.md

    - name: Push changes
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ github.token }}
        branch: ${{ github.head_ref }}
